receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - "*"

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "https://<OBSERVE CUSTOMER ID>.collect.observeinc.com/v2/otel"
    headers:
      authorization: "Bearer <OBSERVE INGEST TOKEN>"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]

